services:
  redis:
    image: redis
    container_name: cache
  app:
    build: ./
    ports:
      - 8080:8080
    links:
      - redis
    env_file:
      - .env
    command:
      sh -c 'node ./api/server.js'
  